<a href="https://colab.research.google.com/github/DVAnumala/smartbridge_assignments/blob/main/assingment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

Q1. Create a pandas dataframe (Dataframe name as 'df') with numpy random values (4 features and 4 observations)

In [4]:
data = np.random.rand(4,4)
df = pd.DataFrame(data, columns=['Type-A','Type-B','Type-C','Type-D'])
df

     Type-A    Type-B    Type-C    Type-D
0  0.917361  0.192524  0.519673  0.213563
1  0.968857  0.596955  0.023628  0.058879
2  0.981168  0.326267  0.796294  0.048620
3  0.040450  0.844116  0.098600  0.429326

Q2. Rename Q1 'df' dataframe column names to 'Random Value 1','Random Value 2','Random Value 3' and 'Random Value 4'

In [6]:
new_colnames = ['Random Value 1','Random Value 2','Random Value 3','Random Value 4']
df.columns = new_colnames
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.917361        0.192524        0.519673        0.213563
1        0.968857        0.596955        0.023628        0.058879
2        0.981168        0.326267        0.796294        0.048620
3        0.040450        0.844116        0.098600        0.429326

Q3. Find the descriptive statistics of the 'df' dataframe

In [7]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.726959        0.489965        0.359549        0.187597
std          0.458507        0.289907        0.363924        0.177942
min          0.040450        0.192524        0.023628        0.048620
25%          0.698133        0.292831        0.079857        0.056314
50%          0.943109        0.461611        0.309136        0.136221
75%          0.971935        0.658745        0.588828        0.267504
max          0.981168        0.844116        0.796294        0.429326

Q4. Check for the null values in 'df' and find the data type of the columns

In [8]:
df.isnull().any()

Random Value 1    False
Random Value 2    False
Random Value 3    False
Random Value 4    False
dtype: bool

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      float64
 1   Random Value 2  4 non-null      float64
 2   Random Value 3  4 non-null      float64
 3   Random Value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

Q5. Display the 'Random Value 2' and 'Random Value 3' columns with locations method and index location method

In [10]:
df.loc[:,'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0        0.192524        0.519673
1        0.596955        0.023628
2        0.326267        0.796294
3        0.844116        0.098600

In [11]:
df.iloc[:,1:3]

   Random Value 2  Random Value 3
0        0.192524        0.519673
1        0.596955        0.023628
2        0.326267        0.796294
3        0.844116        0.098600